spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/swift_app
    username: swift_app
    password: swift_app
    driverClassName: org.postgresql.Driver

periodic:
  payment-cache-ttl-minutes: 30

telegram:
  token: 5463053454:AAGpItf72lRM2u4MYSa95OuZRYx9Q0Zi_YQ
  admin-chat: 93179449
  level: INFO

payment:
  daysBeforeSuspended: 14